### ISSUE TITLE
Add support for .NET 5.0

### ISSUE THREAD

**Issue by hellfirehd** [mrpmorris/blazor-validation#19]
The following exception is thrown during validation in the client:
```text
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Number of parameters specified does not match the expected number.
System.Reflection.TargetParameterCountException: Number of parameters specified does not match the expected number.
   at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at PeterLeslieMorris.Blazor.Validation.Extensions.EditContextExtensions.NotifyPropertyChanged(EditContext editContext, Object instance, String propertyName)
   at PeterLeslieMorris.Blazor.Validation.Extensions.EditContextExtensions.ValidateProperty(EditContext editContext, Object instance, PropertyInfo property, HashSet`1 validatedObjects)
   at PeterLeslieMorris.Blazor.Validation.Extensions.EditContextExtensions.ValidateObject(EditContext editContext, Object instance, HashSet`1 validatedObjects)
   at PeterLeslieMorris.Blazor.Validation.Extensions.EditContextExtensions.ValidateObjectTree(EditContext editContext)
   at CPCA.WebUI.Client.Pages.ContactInformation.HandleSubmit(EditContext context) in D:\Source\CPCAv4\source\CPCA.WebUI\Client\Pages\ContactInformation.razor.cs:line 40
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

This is caused by a dependency on an internal method on the EditContext.  In `netstandard2.1` the signature is:
```csharp
internal FieldState GetFieldState(in FieldIdentifier fieldIdentifier, bool ensureExists);
```
In `net5.0` the previous method has been replaced by two new methods:
```csharp
internal FieldState? GetFieldState(in FieldIdentifier fieldIdentifier);
internal FieldState GetOrAddFieldState(in FieldIdentifier fieldIdentifier);
```

I'm working on a pull request that addresses this but need guidance on how you would like to proceed.  My preference would be a Major Version increment and simply drop support for `netstandard2.1` as trying to multi-target both `netstandard2.1` and 'net5.0' is a PITA.

**Comment by Dmo16** [comment]
Do we know if this is something that will be merged? Pulled the trigger on .NET 5.0 today but will need to make some decisions whether or not to rollback based on the roadmap of this package.

**Comment by mrpmorris** [comment]
I've used your changes without the additional demos. Would you give 1.5.0-beta-1 a try and let me know if you are happy with it?

**Comment by hellfirehd** [comment]
Seems like it's working.

**Comment by mrpmorris** [comment]
Thanks for your PR!

I mostly took the code you wrote.
